const IMAGE_FIT_FILL = 'fill'
const IMAGE_FIT_CONTAIN = 'contain'
const IMAGE_FIT_COVER = 'cover'
const IMAGE_FIT_NONE = 'none'
const IMAGE_FIT_SCALE_DOWN = 'scale-down'

export const IMAGE_FIT = {
  [IMAGE_FIT_FILL]: IMAGE_FIT_FILL,
  [IMAGE_FIT_CONTAIN]: IMAGE_FIT_CONTAIN,
  [IMAGE_FIT_COVER]: IMAGE_FIT_COVER,
  [IMAGE_FIT_NONE]: IMAGE_FIT_NONE,
  scaleDown: IMAGE_FIT_SCALE_DOWN,
}
